In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('./final_data_set.csv')

In [5]:
features = [
    "Prev_Return",
    "Prev_Range_Pct",
    "Prev_Direction",

    "Asian_Return",
    "Asian_Range_Pct",
    "Asian_Direction",

    "London_Return",
    "London_Range_Pct",
    "London_Direction",

    "Dist_Prev_High",
    "Dist_Prev_Low"
]

X = df[features]

y = df["Target"]


In [6]:
n_features = X.shape[1]

W = np.zeros(n_features)

b = 0

In [7]:
print(W)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0


In [8]:
z = np.dot(X, W) + b

In [9]:
print(z)

[0. 0. 0. ... 0. 0. 0.]


In [10]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [11]:
probability= sigmoid(z)

In [12]:
print(probability)

[0.5 0.5 0.5 ... 0.5 0.5 0.5]


In [13]:
prediction = (probability >= 0.5).astype(int)

In [14]:
print(prediction) # all 0.5

[1 1 1 ... 1 1 1]


<html><h1>logL(β)=∑n​[yi​log(pi​)+(1−yi​)log(1−pi​)]</h1></html>


In [15]:
m = len(y)

cost = -(1/m) * np.sum(
    y*np.log(probability)
    +
    (1-y)*np.log(1-probability)
)

print(cost)

0.6931471805599453


<p>
  $$dw = \frac{1}{m} X^T (P - Y)$$
</p>
<p>
  $$db = \frac{1}{m} \sum (P - Y)$$
</p>


In [16]:
dw = (1 / m) * np.dot(X.T, (probability - y))

db = (1 / m) * np.sum(probability - y)

print("dw Shape :", dw.shape)
print("db :", db)

dw Shape : (11,)
db : -0.013920584208124144


In [17]:
learning_rate = 0.01

In [18]:
W = W - learning_rate * dw

b = b - learning_rate * db

In [19]:

print(W)


print(b)

[ 7.73966518e-05  4.66101942e-04  2.96668188e-05  6.00833817e-05
  4.57614288e-04  1.30077590e-04  1.69627893e-04  5.12537555e-04
  1.89411228e-04 -3.82230514e-04 -2.44361668e-05]
0.00013920584208124145


In [20]:
z = np.dot(X, W) + b

probability = sigmoid(z)

print(probability)

[0.50071132 0.50143703 0.50143697 ... 0.50092512 0.50105845 0.50073856]


In [25]:
learning_rate = 0.01
epochs = 1000

m = len(y)

cost_history = []

for epoch in range(epochs):

    
    z = np.dot(X, W) + b
    probability = sigmoid(z)

    
    probability = np.clip(probability, 1e-15, 1 - 1e-15)

    
    cost = -(1 / m) * np.sum(
        y * np.log(probability) +
        (1 - y) * np.log(1 - probability)
    )

    cost_history.append(cost)

    
    dw = (1 / m) * np.dot(X.T, (probability - y))
    db = (1 / m) * np.sum(probability - y)

    
    W = W - learning_rate * dw
    b = b - learning_rate * db

   
    # if (epoch + 1) % 100 == 0:
    #     print(f"Epoch {epoch+1} | Cost = {cost:.6f}")

In [26]:
z = np.dot(X, W) + b
probability = sigmoid(z)

prediction = (probability >= 0.5).astype(int)

print(prediction[:100])

[1 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 0 0 0 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 0 1
 1 0 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 1 1 0]
